using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler
{      
    //Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

    //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


    public class EvenFibonacciNumbers
    {
        public static void Calculate()
        {
            List<int> numbers = new List<int>();

            numbers=  GetFibonacciNumbers(0, 1, numbers);
            int result = Sum(numbers);

            Console.WriteLine(result);
            Console.ReadKey();
        }


        public static List<int> GetFibonacciNumbers(int number1, int number2, List<int> numbers)
        {
            if(number1 + number2 < 4000000)
            {
                int temp = number1 + number2;
                number1 = number2;
                number2 = temp;
                numbers.Add(temp);
                GetFibonacciNumbers(number1, number2, numbers);
            }
            return numbers;
        }

        public static int Sum(List<int> numbers)
        {
            int result = 0;
            foreach (var item in numbers)
            {
                //if is even then some
                if(item % 2 == 0 )
                {
                    result += item;
                }
             
            }
            return result;
        }
    }
}
